### ISSUE TITLE
Changing track immediately 

### ISSUE THREAD

**Issue by ukmoose** [shbert/node-red-contrib-sonos#1]
Many thanks for creating this I can hopefully replace my mess of SOAP calls in node-red

I mainly use my sonos to listen to radio stations.  So adding to a queue doesn't make much sense as the existing track doesn't end ( and theres no FWD / REW icons displayed when playing a radio stream within the sonos apps)

So what I want to be able to do is replicate an immediate change of radio station.

http://<sonos ip address>:1400/support/review  (triggered xml dump > Performance Counters)
 shows the stream to be of this format:
hls-radio://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/llnw/bbc_radio_two.m3u8

any ideas?

**Comment by shbert** [comment]
Have you tried to use the "next" command in the queue node (in the background it implements the queueNext() command from the sonos library), it should change immediately to the uri handed over. I've not tested it yet, but I have the same requirement here, so I'll test it next time.

**Comment by shbert** [comment]
In the git repository I just added the directplay function. After testing I can publish that to the npm repository.

**Comment by ukmoose** [comment]
Yes, i had tried "next" and it hadn't worked.   But the github version works with hls-radio:// urls.   Many thanks!
