### ISSUE TITLE
Set Title when using a Radio-URL

### ISSUE THREAD

**Issue by jstrobel** [shbert/node-red-contrib-sonos#4]
When i am using a Radio-URL as Song URI like x-rincon-mp3radio://opml.radiotime.com/Tune.ashx?id=s84203 the Title is set to bigfm-deutschland-128-mp3?usid=0-0-H-M-D-02.
I think there should be other info set as title and/or the possibility to "overrule" it in the play-node.

http://opml.radiotime.com/Describe.ashx?c=nowplaying&id=s7866&partnerId=Sonos&serial=00-0E-58-25-41-12:4 shows more Info.

albumArtURI would be nice too.

**Comment by jstrobel** [comment]
Or is this a issue with node sonos?

**Comment by svrooij** [comment]
With the current version of the [sonos library](https://github.com/bencevans/node-sonos/blob/master/lib/sonos.js#L87) the title for radio stations is set to ‘TuneIn radio’ if it isn’t specified.

**Comment by jstrobel** [comment]
Thank you. I have updated it but haven't success so far. I think i have to debug deeper, but i close this issue so far.
