### ISSUE TITLE
New npm package

### ISSUE THREAD

**Issue by jstrobel** [shbert/node-red-contrib-sonos#7]
Is there a chance that you publish a new npm package in the next time? Would be great thank you.

**Comment by Rolf-M** [comment]
you should also update the version in package.json :-)
And by the way, there is a new improved version of the underlaying node-sonos, so if you would change the dependency in the package file, npm would update node-sonos... Would be cool...

**Comment by jstrobel** [comment]
@Rolf-M I changed it, but i am not 100% sure if i changed everything needed.

**Comment by shbert** [comment]
I'll come back on weekend. Try to publish a new release. Btw. I'll also try to include some of the good ideas from the other forks, any preferred wishes?

**Comment by Rolf-M** [comment]
I'd still love to have the group/ungroup feature. It's now supported in "node-sonos", so should be possible to implement. And the search function would be nice, too.
Thanks

**Comment by shbert** [comment]
Was a bit more work than I thought, so only updates and the first version of the group node were added. Hope it works for you. npm package published.

**Comment by jstrobel** [comment]
Thanks @shbert for the new package.
